### ISSUE TITLE
where is grapesjs-echarts.min.js file i want to use this plugin but i am not able to

### ISSUE THREAD

**Issue by Rasazna** [jvas28/grapesjs-echarts#3]

**Comment by jvas28** [comment]
Hi Rasazna,
It's here, https://unpkg.com/grapesjs-echarts
You can see a working example here: https://codepen.io/jvas28/pen/ZEGByOq

**Comment by Rasazna** [comment]
it is not there in the github repository?

**Comment by Rasazna** [comment]
Anyways thank you so much its working great. can i get the unminified version of this file i want to know how to implement **high-charts** in the same way as you used in this plugin I want to design the trait manager according to my needs .

**Comment by jvas28** [comment]
Minified version shouldn't be in the repo given that it has a mechanism to build it. You can clone the repo, install dependencies and then run `npm run build` and will get dist folder with minified version. 
This is open source, the implementation is in `src` folder, so you can check the unminified code there.

**Comment by Rasazna** [comment]
thank you so much very helpful this was.
