### ISSUE TITLE
[Question] Updating label name ?

### ISSUE THREAD

**Issue by Lerdouille** [jvas28/grapesjs-echarts#5]
Hi,

is it possible to allow the update of label's name ?
I would like to change the strings "Theme", "Select a theme", Item" etc... by some translations ?

Best regards

**Comment by jvas28** [comment]
@Lerdouille sure, I'll add them. Just bare with me a little :)

**Comment by jvas28** [comment]
@Lerdouille now you can use plugin opt property intl 
```
...
pluginsOpts: {
          "grapesjs-echarts": {
            intl: {
              locale: "en",
              messages: {
                en: {
                  components: {
                    bars: { name: "My new bars name" },
                  },
                },
              },
            },
          },
        },
...
```

you can customize the following messages
```
{
    theme: {
      label: "Theme",
      placeholder: "Select a theme",
    },
    items: {
      label: "Items",
      category: "Category",
      color: "Color",
      save: "Save",
    },
    category: "Charts",
    components: {
      bars: {
        name: "Bars Chart",
      },
      pie: {
        name: "Pie Chart",
      },
      donut: {
        name: "Donut Chart",
      },
      custom: {
        name: "Custom Chart",
      },
    },
  }
```

**Comment by Lerdouille** [comment]
Hi,

thanks a lot for the upgrade !
Is it possible to have in the repository, a folder called dist with a minify js file with your plugin content ?
Like this (for another plugin) :  https://github.com/artf/grapesjs-component-countdown/tree/master/dist

I have found a minify source for your previous version but i can't the updated one...

Thanks again for your grate job !

Best regards

**Comment by jvas28** [comment]
Thanks for the support! 😄 

You can find the minified version [here - unpkg](https://unpkg.com/grapesjs-echarts@0.0.18/dist/grapesjs-echarts.min.js)  

I'm not adding dist folder to repo, you can easily build it if needed by cloning the repo and building it! sorry for that. But everytime I publish to npm the minified version will be updated will be at [Unpkg](https://unpkg.com/grapesjs-echarts@0.0.18/dist/grapesjs-echarts.min.js)
or simply by adding 
`npm i grapesjs-echarts`
`yarn add grapesjs-echarts`

Regards!
